export const TODOS_FILTER_TYPE = {
  SHOW_ALL: 'SHOW_ALL',
  SHOW_COMPLETED: 'SHOW_COMPLETED',
  SHOW_PENDING: 'SHOW_PENDING',
}

export const TODO_MENU_OPTIONS = {
  EDIT_TODO: 'EDIT_TODO',
  DELETE_TODO: 'DELETE_TODO',
}

export default {}
